project:
  type: website
website:
  title: "Data Solutions for ILSA"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About your butt
format:
  html:
    theme: cosmo
    toc: true
