project:
  type: website

website:
  title: "Data Solutions for ILSA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - blog.qmd
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true 
